[package]
name = "rain_viewer"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

tokio = { version = "1.12", features = ["full"] }
reqwest = "0.11"
